spring:
  ### Profile ###
  profiles: default

### Persistence ###
#### MongoDB ####
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: servicebroker
      username: marco
      password: computer-93

### Deployment ###
#### Existing CouchDB Server/Cluster ####
existing:
  endpoint:
    hosts:
      - ip: localhost
        name: couchdb
        port: 5984
    port: 5984
    database: _users
    username: admin
    password: admin

### Service Key Generation ###
#### HAProxy ####
haproxy:
  uri: https://haproxy.cf.dev.eu-de-central.msh.host/agents/596c5b4d57920aaa9fdffae4/schemas?type=listen
  auth:
    token: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

### Login Information ###
login:
  username: admin
  password: cloudfoundry
  role: USER

## OpenStack Settings ## (OPTIONAL)
#openstack:
#  endpoint:
#  user:
#    username:
#    password:
#    domainName:
#  project:
#    domainName:
#    projectName:
#  networkId:
#  subnetId:
#  imageId:
#  keypair:
#  cinder:
#    az: zone00
catalog:
  services:
    - id: sample-local
      name: sample-local
      description: Sample Instances
      bindable: true
      dashboard:
        url: http://localhost:8080
        #url:$endpoint_uri
        auth_endpoint: $uaa_uri
        #auth_endpoint: $uaa_uri
      dashboard_client:
        id: sample
        secret: sample
        redirect_uri: http://localhost:8080
      plan_updateable: true
      plans:
      - id: 5678-1234
        name: m
        description: A simple sample Local plan.
        free: false
        volumeSize: 25
        volumeUnit: M
        platform: EXISTING_SERVICE
        connections: 4
      - id: 1234-5678
        name: s
        description: Another simple sample Local plan.
        free: false
        volumeSize: 25
        volumeUnit: G
        platform: EXISTING_SERVICE
        connections: 4