
---
name: couchdb-dedicated

releases:
- name: couchdb-dedicated
  version: latest
- name: osb-bosh-monitoring
  version: latest
- name: osb-bosh-haproxy
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 3

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: couchdb
  instances: 3
  vm_type: minimal
  stemcell: default
  persistent_disk_type: 10GB
  azs:
  - z1
  jobs:
  - name: couchdb2
    release: couchdb-dedicated
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: couchdb_exporter
    release: osb-bosh-monitoring
  networks:
  - name: service
  properties:
    auth:
      username:
      password:
      port: 5984
- name: haproxy
  instances: 1
  vm_type: minimal
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  jobs:
  - name: haproxy
    release: osb-bosh-haproxy
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: haproxy_exporter
    release: osb-bosh-monitoring
  properties:
    ha_proxy:
      binding_ip: 0.0.0.0
      disable_http: false
      http_frontend_port: 5984
      backend_port: 5984
      stats_enable: true
      stats_user: admin
      stats_password: admin
